Repository Sudokuru/Frontend, pull requests merged in 2023-03, with the labels that each got.

#60 Implementing Pressable & MobileSafeView
  sudokuru/app/Components/Sudoku Board/SudokuBoard.tsx
  sudokuru/app/Pages/HomePage.tsx
  sudokuru/app/Pages/LandingPage.tsx
  sudokuru/app/Pages/ProfilePage.tsx
  sudokuru/app/Pages/PuzzlePage.tsx
  sudokuru/app/Pages/StatisticsPage.tsx
  sudokuru/app/Pages/SudokuPage.tsx
  sudokuru/package-lock.json
  sudokuru/package.json
Labels: enhancement

#62 Adding carousel buttons and making Lesson Icons clickable
  sudokuru/app/Components/Home/Carousel.tsx
Labels: enhancement

#63 Physical Numberpad Support Update
  sudokuru/app/Components/Sudoku Board/SudokuBoard.tsx
Labels: enhancement

#70 Updating expo version to 48
  sudokuru/package-lock.json
  sudokuru/package.json
Labels: dependencies

#72 Revert "Updating expo version to 48"
  sudokuru/package-lock.json
  sudokuru/package.json
Labels: dependencies

#71 Cell Border Highlighting
  sudokuru/app/Components/Sudoku Board/SudokuBoard.tsx
Labels: enhancement

#73 Switching from Webpack to Metro for web bundling
  sudokuru/app.config.ts
  sudokuru/app/Components/Auth0/LoginButton.tsx
  sudokuru/app/Components/Learn/BoardBox.tsx
  sudokuru/app/Components/Learn/LessonCard.tsx
  sudokuru/app/Pages/HomePage.tsx
  sudokuru/app/Pages/LandingPage.tsx
  sudokuru/app/Pages/ProfilePage.tsx
  sudokuru/app/Pages/PuzzlePage.tsx
  sudokuru/app/Pages/StatisticsPage.tsx
  sudokuru/app/Pages/SudokuPage.tsx
  sudokuru/app/Styling/ThemeColors.tsx
  sudokuru/app/Types/Auth0/placeholder.ts
  sudokuru/app/Types/env/env.d.ts
  sudokuru/app/assets/adaptive-icon.png
  sudokuru/app/assets/erase.svg
  sudokuru/app/assets/favicon.png
  sudokuru/app/assets/hint.svg
  sudokuru/app/assets/icon.png
  sudokuru/app/assets/note.svg
  sudokuru/app/assets/noteoff.svg
  sudokuru/app/assets/splash.png
  sudokuru/app/assets/undo.svg
  sudokuru/babel.config.js
  sudokuru/config.ts
  sudokuru/package-lock.json
  sudokuru/package.json
Labels: dependencies

#75 Topbar, Timer, Pause/Resume Added
  sudokuru/app/Components/Sudoku Board/SudokuBoard.tsx
Labels: enhancement

#85 Fixing inverted scrolling carousel for web (again)
  Documentation/DesignDecisions/Carousel.md
  sudokuru/app/Components/Home/Carousel.tsx
  sudokuru/patches/react-native-reanimated-carousel+3.3.0.patch
Labels: bug

#84 getDrill now calls backend
  .github/workflows/pipeline.yml
  sudokuru/README.md
  sudokuru/app/Pages/DrillPage.tsx
  sudokuru/package-lock.json
  sudokuru/package.json
Labels: enhancement

#87 Adding Developer Documentation
  Documentation/Backend API Calls/Code Example.md
  Documentation/Backend API Calls/Troubleshooting.md
  sudokuru/.env.template
  sudokuru/README.md
  sudokuru/package-lock.json
  sudokuru/package.json
Labels: documentation

#90 Adding StartGame
  sudokuru/app/Pages/SudokuPage.tsx
  sudokuru/package-lock.json
  sudokuru/package.json
Labels: enhancement

#93 Save Game
  sudokuru/app/Components/Sudoku Board/SudokuBoard.tsx
  sudokuru/app/Pages/SudokuPage.tsx
  sudokuru/package.json
Labels: enhancement

#100 Resume Game/Prefilled Value Bugfix
  sudokuru/app/Components/Sudoku Board/sudoku.ts
  sudokuru/app/Pages/SudokuPage.tsx
Labels: bug

#119 Fill activeGame Object on Save
  sudokuru/app/Components/Sudoku Board/SudokuBoard.tsx
Labels: enhancement

#126 Drills no longer save state of previous drill sessons
  sudokuru/App.tsx
Labels: bug

#125 User cannot interact with Board Component while in Hint Mode
  sudokuru/app/Components/Sudoku Board/SudokuBoard.tsx
Labels: bug

#131 Fixing drills by adding null checks
  sudokuru/app/Components/Sudoku Board/SudokuBoard.tsx
Labels: bug
